#!/usr/bin/env nbb
;; Compile the Kotoba guest and emit it as an ES module the Worker can import.
;;
;; Two things this does that a bare `amu compile` does not:
;;
;;   1. Absolute paths. `bin/amu` spawns its backend with cwd set to the AMU
;;      repository root, so a relative input path is resolved there and a
;;      perfectly valid file is reported as `:decode / input could not be
;;      read` — the tool saying "I could not find it" in the words of "yours is
;;      malformed". Measured 2026-08-31: the same bytes compile from /tmp and
;;      fail from this repository.
;;
;;   2. The guest's identity, as a build-time fact. wrangler bundles the
;;      `.wasm` itself and hands the Worker a `WebAssembly.Module`, which
;;      cannot be hashed at runtime — its bytes are gone. So the digest is
;;      computed HERE, where the bytes exist, and travels beside the module as
;;      a constant the Worker reports rather than one it verifies. Saying that
;;      out loud is the point: a digest a host cannot check is provenance, not
;;      admission, and the two should not be confused.
(ns build-guest
  (:require ["node:child_process" :as cp]
            ["node:crypto" :as crypto]
            ["node:fs" :as fs]
            ["node:path" :as path]
))

(def root (js/process.cwd))
(def amu (path/resolve root "../../kotoba-lang/amu/bin/amu"))
(def source (path/join root "guest" "decisions.kotoba"))
(def wasm (path/join root "guest" "decisions.wasm"))
(def out (path/join root "guest" "decisions.wasm.mjs"))
(def vendor (path/join root "worker" "vendor"))

(defn- copy-pinned!
  ;; Copy a file out of a west-pinned checkout, recording where it came from
  ;; and what it hashed to. A Worker bundle cannot reach outside itself, so
  ;; these files have to travel inside it; recording the origin is what keeps
  ;; the copy from becoming a fork nobody notices.
  [from to note]
  (let [bytes (fs/readFileSync from)
        digest (-> (crypto/createHash "sha256") (.update bytes) (.digest "hex"))]
    (fs/mkdirSync vendor #js {:recursive true})
    (fs/writeFileSync (path/join vendor to) bytes)
    (println (str "build-guest: vendored " to " (" (.-length bytes) " bytes, sha256 "
                  (subs digest 0 16) "…) from " note))
    digest))

(defn- run! [cmd args]
  (let [r (cp/spawnSync cmd (clj->js args) #js {:stdio "inherit"})]
    (when-not (zero? (.-status r))
      (println "build-guest: FAILED —" cmd (pr-str args))
      (js/process.exit (or (.-status r) 1)))))

(run! amu ["compile" source "--target" "wasm32-browser" "--output" wasm])

(copy-pinned! (path/resolve root "../../kotoba-lang/amu/runtime/browser-host.mjs")
              "browser-host.mjs" "kotoba-lang/amu (west pin)")
(copy-pinned! (path/resolve root "../../kotoba-lang/jp-go-digital-design-system/resources/jp_go_dds/dds.css")
              "dds.css" "kotoba-lang/jp-go-digital-design-system (west pin)")

(let [bytes (fs/readFileSync wasm)
      digest (-> (crypto/createHash "sha256") (.update bytes) (.digest "hex"))]
  (fs/writeFileSync
   out
   (str "// GENERATED by scripts/build-guest.cljs — do not hand-edit.\n"
        "// Source: guest/decisions.kotoba, compiled with amu --target wasm32-browser.\n"
        "// No JVM and no ClojureScript take part in producing this file.\n"
        "export const digest = \"" digest "\";\n"
        "export const bytes = " (.-length bytes) ";\n"))
  (println (str "build-guest: " (.-length bytes) " bytes, sha256 " (subs digest 0 16) "…"))
  (println (str "build-guest: wrote " (path/relative root out))))

;; The two text assets the Worker serves. A Worker bundle has no filesystem, so
;; they travel as strings; generating them here keeps `blueprint.edn` a single
;; file at the repository root (where every other cloud-itonami blueprint is)
;; instead of a second copy under the Worker.
(let [assets (path/join vendor "assets.mjs")
      blueprint (.toString (fs/readFileSync (path/join root "blueprint.edn")) "utf8")
      css (.toString (fs/readFileSync (path/join vendor "dds.css")) "utf8")
      js-string (fn [t] (-> (js/JSON.stringify t)))]
  (fs/writeFileSync
   assets
   (str "// GENERATED by scripts/build-guest.cljs — do not hand-edit.\n"
        "export const blueprintEdn = " (js-string blueprint) ";\n"
        "export const ddsCss = " (js-string css) ";\n"))
  (println (str "build-guest: wrote " (path/relative root assets)
                " (blueprint " (count blueprint) " chars, dds.css " (count css) " chars)")))
